services:
  - type: web
    name: backend-duamiss
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn dashboard_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: duamiss-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false

databases:
  - name: duamiss-db
    databaseName: duamiss
    user: duamiss
    plan: free
